on:
  push:
    branches:
      - master
name: "Build and Release Test Debug"
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.5"
      - run: flutter pub get
      - run: flutter build apk
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{github.run_number}}
          token: ${{secrets.TOKEN}}
      - name: upload artifacts to firebase app distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: release
          file: app/build/outputs/apk/release/app-release.apk

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: build/app/outputs/apk/release/app-release.apk
